Projets/02- Django/02-Pharmax/backend/PharmaxAPI/FAQ/urls.py
from django.urls import path
from .views import index, api, update, add, delete, details
app_name='FAQ'
urlpatterns = [
    path('api/<int:m>/', api, name="api"),
    path('<int:m>/', index, name = "index"),

    path('add/<int:m>/', add, name="add"),

    path('update/<int:m>/<int:id>/', update, name="update"),
    path('delete/<int:m>/<int:id>/', delete, name="delete"),
    path('details/<int:m>/<int:id>/', details, name="details"),

]

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/PharmaxAPI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    #
    path('admin/', admin.site.urls),
    path('', index, name = "index"),
    
    #application
    path('medecine/', include('medecine.urls', namespace='medecine')),#namespace c'est pour differencier les liens de different application
    path('FAQ/', include('FAQ.urls', namespace='FAQ')),
    path('patient/', include('patient.urls', namespace='patient')),
] 


if settings.DEBUG:
    import debug_toolbar 
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/templates/includes/_footer.html
<footer>
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    &copy; Copyright TestDjango &middot; all rights reserved {% now 'Y' %}, CHERIF MOHAMED EL-AMINE.
  </div>
  <!-- Copyright -->
</footer>

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/templates/includes/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light shadow p-3  bg-white d-flex justify-content-between rounded" >
    <a class="navbar-brand" href="#">Pharmax</a>
    <ul class="navbar-nav">
        <li class="nav-item"><a href="{% url 'index' %}" class="nav-link" href="/">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'medecine:index' %}">Medecines</a></li>
        
        <li class="nav-item"><a class="nav-link" href="about/">About</a></li>
        <li class="nav-item"><a class="nav-link" href="contact/">Contact</a></li>
    </ul>
</nav>