Projets/02- Django/02-Pharmax/backend/PharmaxAPI/FAQ/urls.py
from django.urls import path
from .views import index, api, update, add, delete, details
app_name='FAQ'
urlpatterns = [
    path('api/<int:m>/', api, name="api"),
    path('<int:m>/', index, name = "index"),

    path('add/<int:m>/', add, name="add"),

    path('update/<int:m>/<int:id>/', update, name="update"),
    path('delete/<int:m>/<int:id>/', delete, name="delete"),
    path('details/<int:m>/<int:id>/', details, name="details"),

]

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/PharmaxAPI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    #
    path('admin/', admin.site.urls),
    path('', index, name = "index"),
    
    #application
    path('medecine/', include('medecine.urls', namespace='medecine')),#namespace c'est pour differencier les liens de different application
    path('FAQ/', include('FAQ.urls', namespace='FAQ')),
    path('patient/', include('patient.urls', namespace='patient')),
] 


if settings.DEBUG:
    import debug_toolbar 
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/medecine/urls.py
from django.urls import path
from .views import index, api, update, add, delete, details
app_name='medecine'
urlpatterns = [
    path('api/', api, name="api"),
    path('', index, name = "index"),
    
    path('add/', add, name="add"),

    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    path('details/<int:id>/', details, name="details"),

]

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/medecine/models.py
from django.db import models
from patient.models import Patient
from Utils.Errors import Error


# Create your models here.

from django.contrib.auth.models import User   

#---------------------------------------------------------------------------------------------------------------

class Medecine(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField() 
    online = models.BooleanField(default=False)
    slug = models.SlugField(null = False)
    img = models.ImageField(upload_to='', blank = True, null = True)
    patients = models.ManyToManyField(Patient, related_name='medecines', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    errors = {}
    db_errors = {}
    PAGE_TITLE = 'Medecine'
    APP_NAME = 'medecine'
    
    class Meta:
        verbose_name = ('Medecine')
        verbose_name_plural = ('Medecines')


    """
        SETTINGS 
    """
    def get_page_title(self):
        return self.PAGE_TITLE

    def get_app_name(self):
        return self.APP_NAME

    """
        INPUT CONTROL 
    """    
    def input_control(self, title, desc, online, slug, img):
        self.errors.clear()
        title_valid = self.set_title(title)
        desc_valid = self.set_desc(desc)
        online_valid = self.set_online(online)
        slug_valid = self.set_slug(slug)
        img_valid = self.set_img(img)
        return (title_valid and 
                desc_valid and 
                online_valid and 
                slug_valid and 
                img_valid)
    
    def db_input_control(self, type='add'):
        db_title_valid = self.db_set_title(type=type)
        return (db_title_valid)
    
    def db_set_title(self, type):
        self.db_errors.clear()
        count = Medecine.objects.filter(title__iexact = self.title).count()
        if not((count == 0 and type == 'add') or (count <= 1 and type == 'update')):
            self.db_errors[Error.TITLE] = "Title already exist" 
            return False
        return True
    
    def get_errors_dict(self):
        return {key.value: value for key, value in self.errors.items()}
    
    def get_db_errors_dict(self):
        return {key.value: value for key, value in self.db_errors.items()}
    
    """
        SETTER
    """
    def set_title(self, title):
        self.title = title
        if not self.title:
            self.errors[Error.TITLE] = 'Title is empty'
            return False
        return True

    def set_desc(self, desc):
        self.desc = desc
        if not self.desc:
            self.errors[Error.DESC] = 'Description is empty'
            return False
        return True
    
    def set_online(self, online):
        self.online = online
        return True
    
    def set_slug(self, slug):
        self.slug = slug
        if not self.slug:
            self.errors[Error.SLUG] = 'Slug is empty'
            return False
        return True
    
    def set_img(self, img):
        self.img = img
        return True

    """
        GETTER
    """

    def get_title(self):
        return self.title
    
    
    def get_desc(self):
        return self.desc
    
    def get_online(self):
        return self.online
    
    def get_slug(self):
        return self.slug
    
    def get_img(self):
        return self.img
    
    def get_errors(self):
        return self.errors
    
    def __str__(self) -> str:
        return self.title
    

        

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/medecine/forms.py
from django import forms
from .models import Medecine

class MedecineForm(forms.ModelForm):
 
    class Meta:
        model = Medecine
        fields = ('title', 'desc', 'favorite', 'slug', 'img')
        

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/medecine/views.py
from .models import Medecine
from .serializer import MedecineSerializer
import json
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger,EmptyPage
from django.shortcuts import get_object_or_404, render,redirect

from rest_framework.response import Response
from rest_framework.decorators import api_view

import logging

log = logging.getLogger('log')

# Create your views here.

@api_view(['POST','GET'])
def api(request, *args, **kwargs):#request : le resultat de requests.get("url_nav")

    if request.method == 'GET':
        serialized_data = []
        data = []
        p_title = request.GET.get('title') 
        if not p_title:
            data = Medecine.objects.all().order_by('id')
        else:
            data = Medecine.objects.filter(title__iexact=p_title).order_by('id')
        for item in data:
            serialized_data.append(MedecineSerializer(item).data)
        return Response(serialized_data)
    elif request.method == 'POST':
        print(request.data) #request.POST pour le formulaire et pour les requette api c'est request.data
        item = Medecine()
        errors = {}
        if not item.input_control(request.data.get('title'),
                                         request.data.get('desc'),
                                         request.data.get('online'),
                                         request.data.get('slug'),
                                         request.data.get('img')):

            errors = item.get_errors_dict()
        else:
            if not item.db_input_control():
                errors = item.get_db_errors_dict()
            else:
                item.save()
                context = {
                    'item':MedecineSerializer(item).data,
                    'errors':json.dumps({}),
                }
                
        context = {
            'item': MedecineSerializer(item).data,
            'errors': json.dumps(errors),
        }
        
        return Response(context)
    


def index(request):
    data=[]
    if not request.GET.get('key_word'):
        data = Medecine.objects.all().order_by('id')
    else:
        data = Medecine.objects.filter(Q(title__icontains=request.GET.get('key_word')) | Q(desc__icontains=request.GET.get('key_word'))).order_by('id')   
    try:
        paginator = Paginator(data, 5)# data, max_data_in_page
        page = request.GET.get('page',1)
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {
        'data':data, 
        'search': request.GET.get('key_word'), 
        'count':paginator.count,
        'PAGE_TITLE': 'MEDECINES',
        }
    
    return render(request, 'medecine/index.html', context)

def add(request):
    context={
        'item':None,
        'APP_NAME':Medecine().get_app_name(),
        'PAGE_TITLE': 'MEDECINES',
    }
    if request.method== 'POST':
        item = Medecine()
        context=dict()
        if not item.input_control(request.POST.get('title'),
                                         request.POST.get('desc'),
                                         request.POST.get('online')=='on',
                                         request.POST.get('slug'),
                                         request.POST.get('img')):

            errors = item.get_errors_dict()
        else:
            if not item.db_input_control():
                errors = item.get_db_errors_dict()
            else:
                item.save()
                context = {
                    'item':Medecine(),
                    'APP_NAME':Medecine().get_app_name(),
                    'errors':{},
                    'PAGE_TITLE': 'MEDECINES',
                }
                return render(request, 'medecine/add.html', context)
        context = {
            'item': item,
            'APP_NAME':Medecine().get_app_name(),
            'errors': errors,
            'PAGE_TITLE': 'MEDECINES',
        } 

    return render(request, 'medecine/add.html', context)

def delete(request, id=None):
    item = get_object_or_404(Medecine, pk = id) 
    item.delete()
    return redirect('medecine:index')

def update(request, id=None):
    item = Medecine()
    context=dict()

    item = get_object_or_404(Medecine, pk = id) 
    context = {
        'item':item,
        'type':'update',
        'PAGE_TITLE': 'MEDECINES',
    }    
    
    if request.method== 'POST':
        if not item.input_control(request.POST.get('title'),
                                         request.POST.get('desc'),
                                         request.POST.get('online')=='on',
                                         request.POST.get('slug'),
                                         request.POST.get('img')):
            print(item.img.url)
            errors = item.get_errors_dict()
            context={
                'item':item,
                'errors':errors,
                'type':'update',
                'PAGE_TITLE': 'MEDECINES',
            }
        else:
            if not item.db_input_control(type='update'):
                errors = item.get_db_errors_dict()
                context={
                    'item':item,
                    'errors':errors,
                    'type':'update',
                    'PAGE_TITLE': 'MEDECINES',
                }
            else:
                item.save()
                errors= dict()
                
                return redirect('medecine:index')
        context = {
            'item': item,
            'errors': errors,
            'type':'update',
            'PAGE_TITLE': 'MEDECINES',
        } 
    return render(request, 'medecine/update.html', context)


def details(request, id=None):
    item = Medecine()
    context=dict()

    item = get_object_or_404(Medecine, pk = id) 
    context = {
        'item':item,
        'type':'details',
        'PAGE_TITLE': 'MEDECINES',
    }    
    
    return render(request, 'medecine/update.html', context)

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/medecine/templates/medecine/add.html
{% extends 'extends/base.html' %}

<!-- Title -->
{% block title %} {{PAGE_TITLE}} - ADD {% endblock %}

<!-- Header:Banner -->
{% block banner %} 

{% endblock %} 

<!-- Body  -->
{% block body %} 
<div class="col-lg-12 detail-separator">
    
    <h3 class="text-center">
            ADD
    </h3>
    <div class="col-md-6 offset-md-3">
        {% if item %}
            {% if errors|length != 0 %}
                <div class="alert alert-danger" role="alert">
                    Oops! You made a {{errors|length}} little mistake. Please review the highlighted area and try again
                </div>
            {% elif item %}
                <div class="alert alert-success" role="alert">
                    Great! You have successfully added a new record. Feel free to add another one!
                </div>
            {% endif %}
        {% endif %}
    </div>

    <form action="" method="POST" class="col-md-6 offset-md-3">
        
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Doliprane" name="title" value="{{item.title}}">
            <small id="titleHelp" class="form-text text-danger">{{ errors.TITLE }}</small>
        </div>
        <div class="form-group mb-3">
            <label for="desc">Description</label>
            <textarea class="form-control" aria-describedby="descHelp" id="desc" rows="3" placeholder="Ecrire ici la Description medicament" name="desc" >{{item.desc}}</textarea>
            <small id="descHelp" class="form-text text-danger">{{ errors.DESC }}</small>
        </div>
        <div class="form-group mb-3">
            <label for="slug">Slug</label>
            <input type="text" class="form-control" id="slug" aria-describedby="slugHelp" placeholder="doliprane" name="slug" value="{{item.slug}}" >
            <small id="slugHelp" class="form-text text-danger">{{ errors.SLUG }}</small>
        </div>
        <div class="form-group mb-3">
            <input type="file" class="custom-file-input" name="img" value="{{item.img}}" accept="image/*">
        </div>
        <div class="form-check mb-3">
            <input type="checkbox" class="form-check-input" id="online" name="online" {% if item.online %} value="on" checked="checked"{% endif %}>
            <label class="form-check-label" for="online">online</label>
        </div>
        <button type="submit" class="btn btn-primary">
            <i class="fas fa-save"></i>
            Save And Add
        </button>
        {% with app_name=APP_NAME %}
          {% with url_name=app_name|add:":index" %}
          <a href="{% url url_name %}" class="btn btn-danger" class="btn btn-block" onclick="return confirm('Are you sure you want to cancel?');"><i class="fa fa-times" aria-hidden="true"></i>Cancel</a>
          {% endwith %}
        {% endwith %}
    </form>
</div>
{% endblock %}

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/medecine/templates/medecine/index.html
{% extends 'extends/base.html' %}
{% load humanize %}
<!-- Title -->
{% block title %} {{PAGE_TITLE}} {% endblock %}

<!-- Header:Banner -->
{% block banner %} 

{% endblock %} 

<!-- Content  -->
{% block body %} 
<div class="container">
  <!-- Content here -->
  
  <h3 class="text-center">{{PAGE_TITLE}}</h3>
  <div class="mb-3"></div>
  <!-- Search form -->
  <!-- Search form -->
  <!-- Medecine List -->
      <div class="container">
        <form class="form-inline" style="display: flex;" method="GET">
          <input class="form-control form-control-sm mr-3" type="text" placeholder="Search by title or description"
            aria-label="Search" name="key_word" value="{% if search %} {{search}} {% endif %}">
          <!--<a href="{% url 'medecine:index' %}?title={{search}}" type="button" class="btn btn-block" data-mdb-ripple-init> <i class="fas fa-search" aria-hidden="true"></i></a>-->
        </form>
        <div class="mb-1"></div>
        
        <p class="count" style="font-style: italic;font-size: .9rem;">{{data.end_index}}/{{count}} {{ data|length|pluralize:"Medecine,Medecines" }}</p>
        {% with app_name="medecine" %}
          {% with url_name=app_name|add:":add" %}
          <a href="{% url url_name %}" type="button" class="btn btn-success" style="text-align: right;">
              <i class="fa-solid fa-add" style="color:#FFF"></i>ADD
          </a>
          {% endwith %}
        {% endwith %}
       
        <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead class="thead-light">
              <tr>
                <th scope="col" class="fw-bold">#</th>
                <th>Title</th>
                <th >Description</th>
                <th class="text-center">online</th>
                <th>Slug</th>
                <th>Image</th>
                <th>FAQs</th>
                <th></th>
                <th></th>
                <th></th>

              </tr>
            </thead>
         
            <tbody>
              {% for item in data %}
              
              <tr>
               
                <td scope="row" class="fw-bold">{{ data.start_index|add:forloop.counter|add:-1}}</td>
                <td>{{ item.title }}</td>
                <td class="limiter-lignes">{{ item.desc }}</td>
                <td class="text-center">{% if item.online %} 
                  <i class="fa-solid fa-circle-check" style="color:#218838"></i>
                    {% else %}
                      <i class="fa-solid fa-circle-xmark" style="color:#c82333"></i>
                     {% endif %}
                </td>
                <td>{{ item.slug }}</td>
                <td>
                {% if item.img %}
                    <img class="card-img-top" src="{{item.img.url}}" alt="{{item.title}}" style="width:40px; height: 40px;" accept="image/*">
                {% endif %}
                  
                </td>
                <td>
                    <a href="{% url 'FAQ:index' m=item.pk %}" type="button"  type="button" class="btn btn-block" target="_blank" data-mdb-ripple-init><i class="fa-solid fa-circle-question" style="color:#343a40"></i></a>
                </td>

                  <td >
                    {% with app_name=data.0.APP_NAME %}
                    {% with url_name=app_name|add:":details" param=item.pk %}
                    <a href="{% url url_name param %}" type="button"  type="button" class="btn btn-block" data-mdb-ripple-init><i class="fa-solid fa-eye" style="color:#0b5ed7"></i></a>
                    {% endwith %}
                    </td>
                    <td>
                    {% with url_name=app_name|add:":update" param=item.pk %}
                    <a href="{% url url_name param %}" type="button"  type="button" class="btn btn-block" data-mdb-ripple-init><i class="fa-solid fa-pencil" style="color:#218838"></i></a>
                    {% endwith %}
                  </td>
                  <td>
                    {% with url_name=app_name|add:":delete" param=item.pk %}
                    <a href="{% url url_name param %}" type="button"  type="button" class="btn btn-block" onclick="return confirm('Are you sure you want to delete this medecine ?');" data-mdb-ripple-init><i class="fa-solid fa-square-minus" style="color:#c82333"></i></a>
                    {% endwith %}
                    {% endwith %}
                  </td>
                  
                                
              </tr>
              {% empty %}
                  <h2>Pas d'element</h2>
                {% endfor %}

              
            </tbody>
          </table>
        </div>  
        {% if data.has_other_pages %}
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            
              <li class="page-item"><a class="page-link" {% if data.has_previous %} href="?page={{data.previous_page_number}}" {% endif %}>Previous</a></li>
            
            {% for page_number in data.paginator.page_range %}
              <li class="page-item "><a class="page-link {% if data.number == page_number %} bg-light fw-bold {% endif %}" href="?page={{page_number}}" >{{page_number}}</a></li>
            {% endfor %}
            
              <li class="page-item"><a class="page-link" {% if data.has_next %} href="?page={{data.next_page_number}}" {% endif %}>Next</a></li>
            
          </ul>
        </nav>
        {% endif %}
        </div>
          <div class="divider"></div>
          
          
  
</div>
  

{% endblock %}

Projets/02- Django/02-Pharmax/backend/PharmaxAPI/medecine/templates/medecine/update.html
{% extends 'extends/base.html' %}

<!-- Title -->
{% block title %} {{PAGE_TITLE}} - {% if type == 'details' %} DETAILS {% else %} UPDATE {% endif %} {% endblock %}

<!-- Header:Banner -->
{% block banner %} 

{% endblock %} 

<!-- Body  -->
{% block body %} 
<div class="col-lg-12 detail-separator">
    
    <h3 class="text-center">
        {% if type == 'details' %} 
            DETAILS
        {% else %}
            UPDATE
        {% endif %}
      
    </h3>
    
    <form action="" method="POST" class="col-md-6 offset-md-3">
        {% if errors|length != 0 %}
            <div class="alert alert-danger" role="alert">
                Oops! You made a {{errors|length}} little mistake. Please review the highlighted area and try again
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Doliprane" name="title" value="{{item.title}}" {% if type == 'details' %} disabled {% endif %}>
            <small id="titleHelp" class="form-text text-danger">{{ errors.TITLE }}</small>
        </div>
        <div class="form-group mb-3">
            <label for="desc">Description</label>
            <textarea class="form-control" aria-describedby="descHelp" id="desc" rows="3" placeholder="Ecrire ici la Description medicament" name="desc" {% if type == 'details' %} disabled {% endif %}>{{item.desc}}</textarea>
            <small id="descHelp" class="form-text text-danger">{{ errors.DESC }}</small>
        </div>
        <div class="form-group  mb-3">
            <label for="slug">Slug</label>
            <input type="text" class="form-control" id="slug" aria-describedby="slugHelp" placeholder="doliprane" name="slug" value="{{item.slug}}" {% if type == 'details' %} disabled {% endif %}>
            <small id="slugHelp" class="form-text text-danger">{{ errors.SLUG }}</small>
        </div>
        <div class="form-group  mb-3">
            {% if item.img %}
                    <img class="card-img-top" src="{{item.img.url}}" alt="{{item.title}}" style="width:40px; height: 40px;" accept="image/*">
                {% endif %}
            <input type="file" name="img" value="{{item.img}}" {% if type == 'details' %} disabled {% endif %}>
        </div>
        <div class="form-check  mb-3">
           
            <input type="checkbox" class="form-check-input" id="online" name="online" {% if item.online %} value="on" checked="checked"{% endif %} {% if type == 'details' %} disabled {% endif %}>
            <label class="form-check-label" for="online">online</label>
        </div>
        {% if type == 'details' %} 
            {% with app_name=item.APP_NAME %}
                {% with url_name=app_name|add:":index" %}
                    <a href="{% url url_name %}" class="btn btn-danger" class="btn btn-block"><i class="fa fa-arrow-left" style="color:#FFF"></i>List of medecine</a>
                {% endwith %}
            {% endwith %}
        {% else %} 
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-save"></i>
                Save
            </button>
            {% with app_name=item.APP_NAME %}
                {% with url_name=app_name|add:":index" %}
                    <a href="{% url url_name %}" class="btn btn-danger" class="btn btn-block" onclick="return confirm('Are you sure you want to cancel?');"><i class="fa fa-times" aria-hidden="true"></i>
                        Cancel
                    </a>
                {% endwith %}
            {% endwith %}
        {% endif %}
             
    </form>
</div>
{% endblock %}